
name: "cicd"

on:
  push:
    branches:
      - main
  pull_request:
     branches: 
      - manin

permissions:
  contents: read 

jobs:
  nginx-image-bulid:
    runs-on: ubuntu-latest 
    environment: prod

    steps:
      -
         name: checkout repo
         uses: actions/checkout@v2
         with:
            token: ${{secrets.LOGIN_KEY}}
      - 
         name: login to  docker hub 
         uses: docker/login-action@v1
         with:
            username: ${{secrets.DOCKERHUB_USERNAME}}
            password: ${{secrets.DOCKERHUB_TAKEN}}
      - 
         name: setup docker bulid 
         uses: docker/setup-buildx-action@v2 
      - 
        name: bulid image and push to docker hub 
        uses: docker/build-push-action@v4 
        with: 
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{secrets.DOCKERHUB_USERNAME}}/nginx-ubuntu-latest2:${{ github.run_number }}


    


    